### PR TITLE
fixed typo and added d3 hyperlink

### PR DESCRIPTION
**Pull request by jgravois**

### CODE REVIEW

**Comment by jgravois** [comment]
@jschleuss check out Leaflet's L.tileLayer [detectRetina](http://leafletjs.com/reference.html#tilelayer) constructor option :smile:

you can find a working sample that pulls down Esri tiles [here](http://esri.github.io/esri-leaflet/examples/retina-basemap.html).

**Comment by jgravois** [comment]
also renamed `tooltip.html` to `index.html` to satisfy my OCD.

**Comment by jgravois** [comment]
@jschleuss do you want that 'fixed' shapefile of the parking tickets or did you already get the plotting sorted out?

**Comment by jschleuss** [comment]
I haven't yet. Want to just smash it into this repo? as a seperate folder? parking tix?

**Pull request merged**
